[prune]
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/spf13/viper"
  version = "=v1.4.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "=v0.0.5"

[[constraint]]
  name = "github.com/google/go-github"
  version = "=v28.1.1"

# Workaround for https://github.com/golang/dep/issues/1799
# Otherwise ginkgo/gomega won't be pulled in
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "=1.7.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "=1.10.1"

[[constraint]]
  name = "go.uber.org/goleak"
  branch = "master"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "=v1.0.15"



